bookufy/urls.py
from django.urls import path
from . import views

app_name = "bookufy"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("new/", views.NewBookView.as_view(), name="new"),
    path("search/", views.SearchBookView.as_view(), name="search"),
    path("edit/<int:book_id>/", views.EditBookView.as_view(), name="edit"),
    path("detail/<int:book_id>/", views.DetailBookView.as_view(), name="detail"),
    path("delete/<int:book_id>/", views.DeleteBookView.as_view(), name="delete"),
]

bookworm_django/urls.py
from django.contrib import admin
from django.urls import path, include

from bookufy import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('bookufy/', include('bookufy.urls')),
    path('admin/', admin.site.urls),
]

bookufy/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=128)
    author = models.CharField(max_length=64, blank=True)
    genre = models.CharField(max_length=32, blank=True)
    num_of_page = models.PositiveIntegerField(default=0)
    release_year = models.PositiveIntegerField(default=0)
    score = models.FloatField(default=0.0)
    is_public_domain = models.BooleanField(default=False)
    note = models.CharField(max_length=800, blank=True)

    def __str__(self):
        return self.title

bookufy/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.core.paginator import Paginator

from urllib.parse import parse_qs

from .models import Book

class HomeView(View):
    def get(self, request):
        return render(request, "bookufy/home.html")

class IndexView(View):
    def get(self, request):
        item_per_page = 4
        qs = parse_qs(request.META["QUERY_STRING"])
        if "page" not in qs:
            page_num = 1
        else:
            page_num = int(qs["page"][0])
        all_books = Book.objects.all().order_by("id")
        pager = Paginator(all_books, item_per_page)
        page = pager.page(page_num)
        page.number_prev = page_num - 1
        page.number_next = page_num + 1
        prev_page = page.has_previous()
        next_page = page.has_next()
        context = {"books": page.object_list, "page": page, "prev": prev_page, "next": next_page}
        return render(request, "bookufy/index.html", context)

class NewBookView(View):
    def get(self, request):
        return render(request, "bookufy/new.html")

    def post(self, request):
        post = request.POST
        title = post['title']
        num_of_page = post['num_of_page']
        author = post.get("author")
        genre = post.get("genre")
        release_year = post.get("release_year")
        score = post.get("score")
        is_public_domain = post.get("is_public_domain")
        note = post.get("note")
        book = Book(
            title=title,
            num_of_page=num_of_page,
            author=author,
            genre=genre,
            release_year=release_year,
            score=score,
            is_public_domain=is_public_domain,
            note=note
        )
        book.save()
        return redirect(reverse("bookufy:detail", args=[book.id]))

class SearchBookView(View):
    def get(self, request):
        item_per_page = 4
        is_search = False
        search_string = ""
        if "search_string" in request.GET:
            search_string = request.GET["search_string"]
            is_search = True

        qs = parse_qs(request.META["QUERY_STRING"])
        if "page" not in qs:
            page_num = 1
        else:
            page_num = int(qs["page"][0])
            
        filtered_books = \
            Book.objects.filter(title__icontains=search_string)  | \
            Book.objects.filter(author__icontains=search_string) | \
            Book.objects.filter(genre__icontains=search_string)  | \
            Book.objects.filter(note__icontains=search_string)
        
        pager = Paginator(filtered_books, item_per_page)
        page = pager.page(page_num)
        page.number_prev = page_num - 1
        page.number_next = page_num + 1
        prev_page = page.has_previous()
        next_page = page.has_next()
        prev_url = f"?search_string={search_string}&page={page.number_prev}"
        next_url = f"?search_string={search_string}&page={page.number_next}"
        context = {"filtered_books": page.object_list,
                   "page": page, "prev": prev_page, "next": next_page,
                   "prev_url": prev_url, "next_url": next_url, 
                   "search_string": search_string, "is_search": is_search,
                   "query": request.META["QUERY_STRING"]}
        return render(request, "bookufy/search.html", context)

class EditBookView(View):
    def get(self, request, book_id):
        book = get_object_or_404(Book, pk=book_id)
        print(book.is_public_domain)
        context = {"book": book}
        return render(request, "bookufy/edit.html", context)

    def post(self, request, book_id):
        post = request.POST
        book = get_object_or_404(Book, pk=book_id)
        book.title = post["title"]
        book.num_of_page = post["num_of_page"]
        book.author = post.get("author")
        book.genre = post.get("genre")
        book.release_year = post.get("release_year")
        book.score = post.get("score")
        book.is_public_domain = post.get("is_public_domain")
        book.note = post.get("note")
        book.save()
        return redirect(reverse("bookufy:detail", args=[book.id]))

class DetailBookView(View):
    def get(self, request, book_id):
        book = get_object_or_404(Book, pk=book_id)
        context = {"book": book}
        return render(request, "bookufy/detail.html", context)
    
class DeleteBookView(View):
    def get(self, request, book_id):
        book = get_object_or_404(Book, pk=book_id)
        book.delete()
        return redirect(reverse("bookufy:index"))

bookufy/templates/bookufy/.#search.html
deni@arch.4547:1716823193

bookufy/templates/bookufy/detail.html
{% extends "layout/base.html" %}

{% block title %}Detail{% endblock %}

{% block content %}
<section class="container my-5">
  <h1 class="mb-5">Detail of the Book</h1>
  <div>
    <span class="text-body-secondary bg-secondary-subtle py-1 px-2 rounded">Title</span>
    <p class="fs-5 px-2">{{ book.title }}</p>
  </div>
  <div>
    <span class="text-body-secondary bg-secondary-subtle py-1 px-2 rounded">Author</span>
    <p class="fs-5 px-2">{{ book.author|default:"<i>-</i>" }}</p>
  </div>
  <div>
    <span class="text-body-secondary bg-secondary-subtle py-1 px-2 rounded">Genre</span>
    <p class="fs-5 px-2">{{ book.genre|default:"<i>-</i>" }}</p>
  </div>
  <div>
    <span class="text-body-secondary bg-secondary-subtle py-1 px-2 rounded">Release Year</span>
    <p class="fs-5 px-2">{{ book.release_year|default:"<i>-</i>" }}</p>
  </div>
  <div>
    <span class="text-body-secondary bg-secondary-subtle py-1 px-2 rounded">Number of Pages</span>
    <p class="fs-5 px-2">{{ book.num_of_page }}</p>
  </div>
  <div>
    <span class="text-body-secondary bg-secondary-subtle py-1 px-2 rounded">Score</span>
    <p class="fs-5 px-2">{{ book.score|default:"<i>-</i>" }}</p>
  </div>
  <div>
    <span class="text-body-secondary bg-secondary-subtle py-1 px-2 rounded">Is Public Domain</span>
    <p class="fs-5 px-2">{{ book.is_public_domain|default:"<i>-</i>" }}</p>
  </div>
  <div>
    <span class="text-body-secondary bg-secondary-subtle py-1 px-2 rounded">Note</span>
    <p class="fs-5 px-2">{{ book.note|default:"<i>-</i>" }}</p>
  </div>
  <div>
    <a class="btn btn-primary" href="{% url 'bookufy:edit' book.id %}"><i class="bi bi-pencil-square"></i></a>
    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal-{{ book.id }}">
      <i class="bi bi-trash"></i>
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal-{{ book.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
	<div class="modal-content">
	  <div class="modal-header">
	    <h1 class="modal-title fs-5" id="exampleModalLabel-{{ book.id }}">Delete Confirmation</h1>
	    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	  </div>
	  <div class="modal-body">
	    Are you sure you want to delete <b>{{ book.title }}</b>? This action cannot be undone.
	  </div>
	  <div class="modal-footer">
	    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
	    <button class="btn btn-outline-danger" type="button" onclick="deleteBook({{ book.id }})">Yes, delete book</button>
	  </div>
	</div>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript" defer>
  function deleteBook(bookId) {
      // Example: Send a DELETE request using fetch API or redirect to a delete URL
      fetch(`/bookufy/delete/${bookId}/`, {
	  method: 'GET',
	  headers: {
	      'Content-Type': 'application/json',
	      'X-CSRFToken': getCookie('csrftoken'),  // Include CSRF token for security
	  },
      })
	  .then(response => {
	      if (response.ok) {
		  // Optionally, you can add logic to remove the deleted book's entry from the UI
		  window.location.replace("/bookufy");
	      } else {
		  console.error('Failed to delete the book');
	      }
	  })
  .catch(error => {
    console.error('Error:', error);
  });
  }

  // Helper function to get CSRF token from cookies
function getCookie(name) {
  let cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    const cookies = document.cookie.split(';');
    for (let i = 0; i < cookies.length; i++) {
      const cookie = cookies[i].trim();
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}
</script>
{% endblock %}

bookufy/templates/bookufy/edit.html
{% extends "layout/base.html" %}

{% block title %}Edit Book{% endblock %}

{% block content %}
<section class="container my-5">
  <form class="col-md-6" action="{% url 'bookufy:edit' book.id %}" method="post" autocomplete="off">
    {% csrf_token %}
    <div class="mb-3">
      <label for="title" class="form-label">Title</label>
      <input type="text" name="title" class="form-control" id="title" value="{{ book.title }}" spellcheck="false" required>
    </div>
    <div class="mb-3">
      <label for="author" class="form-label">Author</label>
      <input type="text" name="author" class="form-control" id="author" value="{{ book.author }}" spellcheck="false">
    </div>
    <div class="mb-3">
      <label for="genre" class="form-label">Genre</label>
      <input type="text" name="genre" class="form-control" id="genre" value="{{ book.genre }}" spellcheck="false">
    </div>
    <div class="mb-3">
      <label for="release_year" class="form-label">Release Year</label>
      <input type="number" name="release_year" min="0" value="2000" step="1" value="{{ book.release_year }}" class="form-control" id="release_year" spellcheck="false">
    </div>
    <div class="mb-3">
      <label for="score" class="form-label">Score</label>
      <input type="number" min="0.0" max="10.0" step="0.1" value="0.0" name="score" value="{{ book.score }}" class="form-control" id="score" spellcheck="false">
    </div>
    <div class="mb-3">
      <p>Is Public Domain</p>
      <div class="form-check form-check-inline ">
	<input class="form-check-input" type="radio" name="is_public_domain" value="True" id="is_public_domain_yes" {% if book.is_public_domain is True %}checked{% endif %}>
	<label class="form-check-label" for="is_public_domain_yes">
	  Yes
	</label>
      </div>
      <div class="form-check form-check-inline">
	<input class="form-check-input" type="radio" name="is_public_domain" value="False" id="is_public_domain_no" {% if book.is_public_domain is False %}checked{% endif %}>
	<label class="form-check-label" for="is_public_domain_no">
	  No
	</label>
      </div>
    </div>
    <div class="mb-3">
      <label for="num_of_page" class="form-label">Number of Pages</label>
      <input type="number" name="num_of_page" min="0" step="1" value="{{ book.num_of_page }}" class="form-control" id="num_of_page" required>
    </div>
    <div class="mb-3">
      <label class="form-label" for="floatingTextarea">Note</label>
      <textarea class="form-control" id="floatingTextarea" rows="10" value="{{ book.note }}"  name="note"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
</section>
{% endblock %}

bookufy/templates/bookufy/home.html
{% extends "layout/base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
<section class="container my-5">
  <h1>Bookufy Home</h1>
</section>
{% endblock %}

bookufy/templates/bookufy/index.html
{% extends "layout/base.html" %}

{% block title %}Index{% endblock %}

{% block content %}
<section class="container my-5">
  <h1>Index</h1>
  <div class="col-md-6 my-4">
    <ul class="list-group">
      {% if not books %}
      <p>You got no books.</p>
      {% endif %}
      {% for book in books %}
      <li class="list-group-item">
	<span class="text-body-secondary">Title</span>
	<p>{{ book.title }}</p>
	<span class="text-body-secondary">Number of Pages</span>
	<p>{{ book.num_of_page }}</p>
	<p>
	  <a href="{% url 'bookufy:detail' book.id %}" class="text-underline">Read More</a>
	</p>
	<div>
	  <a class="btn btn-primary" href="{% url 'bookufy:edit' book.id %}"><i class="bi bi-pencil-square"></i></a>
	  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal-{{ book.id }}">
	    <i class="bi bi-trash"></i>
	  </button>

	  <!-- Modal -->
	  <div class="modal fade" id="exampleModal-{{ book.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	    <div class="modal-dialog">
	      <div class="modal-content">
		<div class="modal-header">
		  <h1 class="modal-title fs-5" id="exampleModalLabel-{{ book.id }}">Delete Confirmation</h1>
		  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
		</div>
		<div class="modal-body">
		  Are you sure you want to delete <b>{{ book.title }}</b>? This action cannot be undone.
		</div>
		<div class="modal-footer">
		  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
		  <button class="btn btn-outline-danger" type="button" onclick="deleteBook({{ book.id }})">Yes, delete book</button>
		</div>
	      </div>
	    </div>
	  </div>
	</div>
      </li>
      {% endfor %}
    </ul>
    <div class="container my-4">
      {% if prev %}<a class="btn fs-3" href="{% url 'bookufy:index'%}?page={{page.number_prev}}"><i class="bi bi-arrow-left-circle"></i></a>{% endif %}
      {% if next %}<a class="btn fs-3" href="{% url 'bookufy:index' %}?page={{ page.number_next }}"><i class="bi bi-arrow-right-circle"></i></a>{% endif %}
    </div>
  </div>
</section>

<script type="text/javascript" defer>
  function deleteBook(bookId) {
      // Example: Send a DELETE request using fetch API or redirect to a delete URL
      fetch(`/bookufy/delete/${bookId}/`, {
	  method: 'GET',
	  headers: {
	      'Content-Type': 'application/json',
	      'X-CSRFToken': getCookie('csrftoken'),  // Include CSRF token for security
	  },
      })
	  .then(response => {
	      if (response.ok) {
		  // Optionally, you can add logic to remove the deleted book's entry from the UI
		  window.location.reload();  // Reload the page to reflect the changes
	      } else {
		  console.error('Failed to delete the book');
	      }
	  })
  .catch(error => {
    console.error('Error:', error);
  });
  }

  // Helper function to get CSRF token from cookies
function getCookie(name) {
  let cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    const cookies = document.cookie.split(';');
    for (let i = 0; i < cookies.length; i++) {
      const cookie = cookies[i].trim();
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}
</script>
{% endblock %}

bookufy/templates/bookufy/new.html
{% extends "layout/base.html" %}

{% block title %}New Book{% endblock %}

{% block content %}
<section class="container my-5">
  <form class="col-md-6" action="{% url 'bookufy:new' %}" method="post" autocomplete="off">
    {% csrf_token %}
    <div class="mb-3">
      <label for="title" class="form-label">Title</label>
      <input type="text" name="title" class="form-control" id="title" spellcheck="false" required>
    </div>
    <div class="mb-3">
      <label for="author" class="form-label">Author</label>
      <input type="text" name="author" class="form-control" id="author" spellcheck="false">
    </div>
    <div class="mb-3">
      <label for="genre" class="form-label">Genre</label>
      <input type="text" name="genre" class="form-control" id="genre" spellcheck="false">
    </div>
    <div class="mb-3">
      <label for="release_year" class="form-label">Release Year</label>
      <input type="number" name="release_year" min="0" value="2000" step="1" class="form-control" id="release_year" spellcheck="false">
    </div>
    <div class="mb-3">
      <label for="score" class="form-label">Score</label>
      <input type="number" min="0.0" max="10.0" step="0.1" value="0.0" name="score" class="form-control" id="score" spellcheck="false">
    </div>
    <div class="mb-3">
      <p>Is Public Domain</p>
      <div class="form-check form-check-inline ">
	<input class="form-check-input" type="radio" name="is_public_domain" value="True" id="is_public_domain_yes">
	<label class="form-check-label" for="is_public_domain_yes">
	  Yes
	</label>
      </div>
      <div class="form-check form-check-inline">
	<input class="form-check-input" type="radio" name="is_public_domain" value="False" id="is_public_domain_no" checked>
	<label class="form-check-label" for="is_public_domain_no">
	  No
	</label>
      </div>
    </div>
    <div class="mb-3">
      <label for="num_of_page" class="form-label">Number of Pages</label>
      <input type="number" name="num_of_page" min="0" value="0" step="1" class="form-control" id="num_of_page" required>
    </div>
    <div class="mb-3">
      <label class="form-label" for="floatingTextarea">Note</label>
      <textarea class="form-control" id="floatingTextarea" rows="10"  name="note"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
  </form>
</section>
{% endblock %}

bookufy/templates/bookufy/search.html
{% extends "layout/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
<section class="container-md my-5">
  <article class="col-6">
    <h1>Search</h1>
    <form action="{% url 'bookufy:search' %}" method="get" autocomplete="off">
      <div class="input-group mb-3">
	<input type="text" name="search_string" value="{{ search_string }}" class="form-control" aria-describedby="basic-addon2">
	<button id="basic-addon2" class="btn btn-primary"><i class="bi bi-search"></i></button>
      </div>
    </form>
    {% if is_search %}
    <div>
      <ul class="list-group">
	{% for book in filtered_books %}
	<li class="list-group-item">
	  <span class="text-body-secondary">Title</span>
	  <p>{{ book.title }}</p>
	  <span class="text-body-secondary">Number of Pages</span>
	  <p>{{ book.num_of_page }}</p>
	  <p>
	    <a href="{% url 'bookufy:detail' book.id %}" class="text-underline">Read More</a>
	  </p>
	</li>
	{% endfor %}
      </ul>
      <div class="container my-4">
	{% if prev %}<a class="btn fs-3" href="{% url 'bookufy:search' %}{{prev_url}}"><i class="bi bi-arrow-left-circle"></i></a>{% endif %}
	{% if next %}<a class="btn fs-3" href="{% url 'bookufy:search' %}{{next_url}}"><i class="bi bi-arrow-right-circle"></i></a>{% endif %}
      </div>
    </div>
    {% endif %}
  </article>
</section>
{% endblock %}

bookufy/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'bookufy/style.css' %}">
    <link rel="stylesheet" href="{% static 'bookufy/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="{% static 'bookufy/bootstrap.min.js' %}" defer></script>
    <title>{% block title %}My amazing site{% endblock %} | Bookufy</title>
  </head>

  <body>
    {% block sidebar %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container container-md">
	<a class="navbar-brand" href="{% url 'home' %}"><i class="bi bi-book"></i></a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
	  <ul class="navbar-nav">
            <li class="nav-item">
	      <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
	      <a class="nav-link" href="{% url 'bookufy:index' %}">Books</a>
            </li>
            <li class="nav-item">
	      <a class="nav-link" href="{% url 'bookufy:new' %}">New</a>
            </li>
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'bookufy:search' %}">Search</a>
            </li>
	  </ul>
	</div>
      </div>
    </nav>
    {% endblock %}

    <main id="content">
      {% block content %}{% endblock %}
    </main>
  </body>
</html>